### ISSUE TITLE
Devices not being Discovered

### ISSUE THREAD

**Issue by fuzails** [shaonianzhentan/node-red-contrib-ha-mqtt#20]
Hi I have setup as follows:
<img width="643" alt="Screenshot 2022-05-14 at 14 05 36" src="https://user-images.githubusercontent.com/407781/168424964-4aecd7cb-421a-4991-a89b-108eec55167d.png">
<img width="499" alt="Screenshot 2022-05-14 at 14 05 50" src="https://user-images.githubusercontent.com/407781/168424967-6134baba-e0b6-49ca-9342-c49985621363.png">

The configuration for the entity is:

`
{
    "state_topic": "kitchen/downlights/status",
    "command_topic": "kitchen/downlights/switch",
    "brightness_state_topic": "kitchen/downlights/brightness",
    "brightness_command_topic": "kitchen/downlights/brightness/set"
}
`
and have a default entity definition:

`
{
    "qos": 0,
    "payload_on": "ON",
    "payload_off": "OFF",
    "optimistic": false,
    "brightness": true,
    "brightness_scale": 100
}
`

Device is not being discovered in HA or MQTT

Logs show that it does connect:
`
14 May 14:09:58 - [info] Stopping flows
14 May 14:09:58 - [info] Stopped flows
14 May 14:09:58 - [info] Starting flows
14 May 14:09:58 - [info] Started flows
14 May 14:09:58 - [info] [mqtt-broker:HA MQTT] Connected to broker: mqtt://core-mosquitto:1883
`

`
1652527824: New connection from 172.30.32.2:44540 on port 1883.
`

**Comment by shaonianzhentan** [comment]
You need to clear the configuration
`state_topic` `command_topic` `brightness_state_topic` `brightness_command_topic` is default config

**Comment by shaonianzhentan** [comment]
I added a simple example
It contains relatively complete functions
https://github.com/shaonianzhentan/node-red-contrib-ha-mqtt/blob/main/examples/light.json

**Comment by fuzails** [comment]
Thanks.
