### ISSUE TITLE
"Sensor Node" dosen't work

### ISSUE THREAD

**Issue by turutzi** [shaonianzhentan/node-red-contrib-ha-mqtt#23]
Grettings from germany,

the pallet is very nice and works well but the "Sensor Node" dosen't work for me.
I have tried many things but i could't event get HA to recognice the the "Sensor".
Is there any requirement for "Configuraten" for the Sensor node? There is neraly to no documentation or even a example for this node.

Would be nice if there is anywere a working example of the "Sensor Node".

**Comment by shaonianzhentan** [comment]
I have added some examples, which I hope will help you

https://github.com/shaonianzhentan/node-red-contrib-ha-mqtt/tree/main/examples/sensor
