### ISSUE TITLE
Sensor node unit of measurement

### ISSUE THREAD

**Issue by DirkMu** [shaonianzhentan/node-red-contrib-ha-mqtt#25]
Thanks for your work. It really simplifies the creation of entities and devices. 

I am using a sensor node which is supposed to represent a string. That is why I left unit of measurement blank. However unit of measurement is created with the sensor in HA. Can you please adapt the logic accordingly. When unit of measurement is not specified it is not supposed to be used at all.

**Comment by shaonianzhentan** [comment]
#29 fixed
