### ISSUE TITLE
Retain flag

### ISSUE THREAD

**Issue by Sakke64** [shaonianzhentan/node-red-contrib-ha-mqtt#30]
Hi,
thanks for the great node-red add-on.
I've one problem, how to set retain flag true for a config / discovery topic?
Is it possible to set?

**Comment by shaonianzhentan** [comment]
Sorry, I didn't consider this situation. It uses the default method and cannot be modified

![image](https://github.com/shaonianzhentan/node-red-contrib-ha-mqtt/assets/5294022/99405fc9-2a53-4db4-9510-f1b34c766430)

**Comment by Sakke64** [comment]
Fixed now.
