### ISSUE TITLE
Climate config

### ISSUE THREAD

**Issue by jrote1** [shaonianzhentan/node-red-contrib-ha-mqtt#45]
Would it be possible to have mode, fanMode and swingMode configurable so that different options may be specified for the climate component?

**Comment by shaonianzhentan** [comment]
You can modify the default values in the configuration
![image](https://github.com/user-attachments/assets/27596048-b952-4acf-a2d6-679b7e04f2ed)
![image](https://github.com/user-attachments/assets/06c57124-940e-4462-bcc8-11284d34e413)

**Comment by jrote1** [comment]
Ah yes thank you, it looks like it won't update a device that already exists if I then change the configuration. All good now thanks :)
